"""Add tag column to knowledge_files

Revision ID: 1d9d1d525e4d
Revises: 
Create Date: 2025-11-19 16:26:31.982440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9d1d525e4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_files', sa.Column('tag', sa.String(length=50), nullable=True, comment='文件标签/分类'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_files', 'tag')
    # ### end Alembic commands ###
